data:
  build: ./data/
  volumes:
    - ./:/host-datadir
backup:
  build: ./data/
  command: true
  volumes_from:
    - data
web:
  image: nginx:1.9.0
  ports:
    - "80:80"
  volumes:
    - ./www-data:/usr/share/nginx/html
proxy:
  image: jpetazzo/squid-in-a-can:latest
  environment:
    DISK_CACHE_SIZE: 5000
    MAX_CACHE_OBJECT: 1000
  ports:
    - "3128:3128"
  volumes_from:
    - data
registry:
  image: registry:2.0
  ports:
    - "5000:5000"
  volumes_from:
    - data
