data:
  build: ./dataCron/
  volumes:
    - ./:/host-datadir
backup:
  build: ./dataCron/
  command: true
  volumes_from:
    - data
proxy:
  image: jpetazzo/squid-in-a-can:latest
  environment:
    DISK_CACHE_SIZE: 5000
    MAX_CACHE_OBJECT: 1000
  ports:
    - "3128:3128"
  volumes_from:
    - data
registry:
  image: registry:2.0
  ports:
    - "5000:5000"
  volumes_from:
    - data
