- name: "tuned-system | Ensure we do not have unused services enabled"
  action: service name="{{ item }}" state=stopped enabled=no
  with_items:
    - avahi-daemon.service
    - cron.service
    - dhclient.service
    - ntp.service
    - rng-tools.service
    - rsyslog.service
    - syslog.service

- name: "tuned-system | Ensure we have tuned systctl"
  action: sysctl name="{{ item.name }}" value="{{ item.value }}" sysctl_set=yes state=present reload=yes
  with_items:
    - { name: 'vm.overcommit_memory', value: '2' }
    - { name: 'vm.overcommit_ratio', value: '500' }
    - { name: 'vm.swappiness', value: '100' }
    #- { name: 'vm.oom-kill', value: '0' }

- name: "tuned-system | Configure net interface in static mode"
  action: copy src=../files/interfaces dest=/etc/network/interfaces owner=root mode=0644
